HTTPSConnectionPool(host='api.shrtco.de', port=443): Max retries exceeded with url: /v2/shorten?url=https://revisions-permalink-disclaimers-paperback.trycloudflare.com (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f528bcf2890>: Failed to establish a new connection: [Errno -2] Name or service not known'))
HTTPSConnectionPool(host='api.shrtco.de', port=443): Max retries exceeded with url: /v2/shorten?url= (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f528bcf0c10>: Failed to establish a new connection: [Errno -2] Name or service not known'))
